//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public AccountDetail()
        {
            this.BnkTans = new HashSet<BnkTan>();
            this.CashTrans = new HashSet<CashTran>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
        }
    
        public int AccountsDetailId { get; set; }
        public string Particular { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Mode { get; set; }
        public System.DateTime DateTime { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
        public Nullable<int> SaleInvId { get; set; }
        public Nullable<int> PurchInvId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<BnkTan> BnkTans { get; set; }
        public virtual ICollection<CashTran> CashTrans { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual SaleInvoice SaleInvoice { get; set; }
    }
}
