//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddStock
    {
        public int AddStockId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public Nullable<int> PurcPrice { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
    
        public virtual LoginUser LoginUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
