//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BnkTan
    {
        public int BnkTansId { get; set; }
        public string Particular { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> AccountDetailId { get; set; }
        public Nullable<int> ChequeId { get; set; }
        public string MadeBy { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual ChequeList ChequeList { get; set; }
        public virtual AccountDetail AccountDetail { get; set; }
    }
}
