//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTran
    {
        public int CashTransId { get; set; }
        public string Particular { get; set; }
        public int Amount { get; set; }
        public int AccountDetailId { get; set; }
    
        public virtual AccountDetail AccountDetail { get; set; }
    }
}
