//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersAccount
    {
        public int CustomerAccountId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> Debit { get; set; }
        public string Status { get; set; }
        public string BlackList { get; set; }
        public string Particular { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
