//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomersAccounts = new HashSet<CustomersAccount>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CellNumber { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public Nullable<int> Balance { get; set; }
        public string BadDebt { get; set; }
        public string Cnic { get; set; }
    
        public virtual ICollection<CustomersAccount> CustomersAccounts { get; set; }
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
    }
}
