//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcludeProduct
    {
        public int ExId { get; set; }
        public string Particular { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Worth { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual LoginUser LoginUser { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual StockLocation StockLocation { get; set; }
    }
}
