//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseId { get; set; }
        public System.DateTime Date { get; set; }
        public string Particular { get; set; }
        public string Type { get; set; }
        public int Amount { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual LoginUser LoginUser { get; set; }
        public virtual StockLocation StockLocation { get; set; }
    }
}
