//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public LoginUser()
        {
            this.Expenses = new HashSet<Expense>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.ExcludeProducts = new HashSet<ExcludeProduct>();
            this.Withdraws = new HashSet<Withdraw>();
            this.AddFunds = new HashSet<AddFund>();
            this.FundTrans = new HashSet<FundTran>();
            this.AddStocks = new HashSet<AddStock>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string Designation { get; set; }
        public int Status { get; set; }
        public string CellNumber { get; set; }
        public string Image { get; set; }
        public Nullable<int> LocAssigned { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual StockLocation StockLocation { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
        public virtual ICollection<ExcludeProduct> ExcludeProducts { get; set; }
        public virtual ICollection<Withdraw> Withdraws { get; set; }
        public virtual ICollection<AddFund> AddFunds { get; set; }
        public virtual ICollection<FundTran> FundTrans { get; set; }
        public virtual ICollection<AddStock> AddStocks { get; set; }
    }
}
