//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.ExcludeProducts = new HashSet<ExcludeProduct>();
            this.AddStocks = new HashSet<AddStock>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public int SalePrice { get; set; }
        public int PurchasePrice { get; set; }
        public int CompanyId { get; set; }
        public string Status { get; set; }
        public string img { get; set; }
        public Nullable<double> Margin { get; set; }
        public Nullable<int> MinStock { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<ExcludeProduct> ExcludeProducts { get; set; }
        public virtual ICollection<AddStock> AddStocks { get; set; }
    }
}
