//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoice
    {
        public PurchaseInvoice()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.AccountDetails = new HashSet<AccountDetail>();
        }
    
        public int PurchaseInvoiceId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public System.DateTime Date { get; set; }
        public string ReferenceId { get; set; }
        public int Amount { get; set; }
        public int Paid { get; set; }
        public int Balance { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
        public int AccountCredit { get; set; }
        public int StockLocId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> TransactionId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual LoginUser LoginUser { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual StockLocation StockLocation { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual AccountDetail AccountDetail { get; set; }
        public virtual ICollection<AccountDetail> AccountDetails { get; set; }
    }
}
