//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateChangeLog
    {
        public int RateId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public int PreviousPrice { get; set; }
        public int NewPrice { get; set; }
        public System.DateTime Date { get; set; }
    }
}
