//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    
    public partial class sp_purchaseInvoice_Depth_Result1
    {
        public int PurchaseInvoiceId { get; set; }
        public System.DateTime Date { get; set; }
        public string ReferenceId { get; set; }
        public int Amount { get; set; }
        public int Paid { get; set; }
        public int Balance { get; set; }
        public string Status { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string CompanyName { get; set; }
        public string Name { get; set; }
        public string SupplierName { get; set; }
        public string Branch { get; set; }
        public string Title { get; set; }
    }
}
