//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    
    public partial class sp_stockList_Result2
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public int SalePrice { get; set; }
        public int PurchasePrice { get; set; }
        public int CompanyId { get; set; }
        public string Status { get; set; }
        public string img { get; set; }
        public int BrandId { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string Logo { get; set; }
        public int StockId { get; set; }
        public int ProductId1 { get; set; }
        public int Quantity { get; set; }
        public int LocationId { get; set; }
        public int StockLocId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Supervisor { get; set; }
        public string ContactNumber1 { get; set; }
    }
}
