//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocation
    {
        public StockLocation()
        {
            this.Expenses = new HashSet<Expense>();
            this.LoginUsers = new HashSet<LoginUser>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.Stocks = new HashSet<Stock>();
            this.ExcludeProducts = new HashSet<ExcludeProduct>();
            this.Withdraws = new HashSet<Withdraw>();
            this.AddFunds = new HashSet<AddFund>();
            this.FundTrans = new HashSet<FundTran>();
        }
    
        public int StockLocId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Supervisor { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<LoginUser> LoginUsers { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<ExcludeProduct> ExcludeProducts { get; set; }
        public virtual ICollection<Withdraw> Withdraws { get; set; }
        public virtual ICollection<AddFund> AddFunds { get; set; }
        public virtual ICollection<FundTran> FundTrans { get; set; }
    }
}
