//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HafizG
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAccount
    {
        public int SupplierAccDetailId { get; set; }
        public int SupplierId { get; set; }
        public string Particular { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> Debit { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
